export const FETCH_EMPLOYEES_COMPLETE = "FETCH_EMPLOYEES_COMPLETE";

export const SAVE_NEW_EMPLOYEE_COMPLETE = "SAVE_NEW_EMPLOYEE_COMPLETE";
export const SHOW_NEW_EMPLOYEE_MODAL = "SHOW_NEW_EMPLOYEE_MODAL";
export const HIDE_NEW_EMPLOYEE_MODAL = "HIDE_NEW_EMPLOYEE_MODAL";

export const EDIT_EMPLOYEE_COMPLETE = "EDIT_EMPLOYEE_COMPLETE";
export const SHOW_EDIT_EMPLOYEE_MODAL = "SHOW_EDIT_EMPLOYEE_MODAL";
export const HIDE_EDIT_EMPLOYEE_MODAL = "HIDE_EDIT_EMPLOYEE_MODAL";

export const DELETE_EMPLOYEE_COMPLETE = "DELETE_EMPLOYEE_COMPLETE";
