export const FETCH_EMPLOYEES_COMPLETE = "FETCH_EMPLOYEES_COMPLETE";

export const ADD_EMPLOYEE_COMPLETE = "ADD_EMPLOYEE_COMPLETE";
export const SHOW_ADD_EMPLOYEE_MODAL = "SHOW_ADD_EMPLOYEE_MODAL";
export const HIDE_ADD_EMPLOYEE_MODAL = "HIDE_ADD_EMPLOYEE_MODAL";

export const EDIT_EMPLOYEE_COMPLETE = "EDIT_EMPLOYEE_COMPLETE";
export const SHOW_EDIT_EMPLOYEE_MODAL = "SHOW_EDIT_EMPLOYEE_MODAL";
export const HIDE_EDIT_EMPLOYEE_MODAL = "HIDE_EDIT_EMPLOYEE_MODAL";

export const DELETE_EMPLOYEE_COMPLETE = "DELETE_EMPLOYEE_COMPLETE";
