export const FETCH_EMPLOYEES_COMPLETE = "FETCH_EMPLOYEES_COMPLETE";

export const SAVE_SCHEDULE = "SAVE_SCHEDULE";
export const MODIFY_SCHEDULE = "MODIFY_SCHEDULE";

export const SHOW_PERIOD_SELECTOR = "SHOW_PERIOD_SELECTOR";
export const HIDE_PERIOD_SELECTOR = "HIDE_PERIOD_SELECTOR";
