export const FETCH_ROTA_COMPLETE = "FETCH_ROTA_COMPLETE";

export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
export const SHOW_EDIT_SCHEDULE_MODAL = "SHOW_EDIT_SCHEDULE_MODAL";
export const HIDE_EDIT_SCHEDULE_MODAL = "HIDE_EDIT_SCHEDULE_MODAL";
